// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hocflodaiymqnighjssu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvY2Zsb2RhaXltcW5pZ2hqc3N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NzQwMzUsImV4cCI6MjA2OTM1MDAzNX0.kH1NyD1k3fkQEWyGJqml9UcYZiayO5U7stKuiyjV6Lo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});