// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmlalkapjbyihmswtxbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptbGFsa2FwamJ5aWhtc3d0eGJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MDI4MzYsImV4cCI6MjA2ODk3ODgzNn0.VE-xxP9OcYynOkCfGXJz_aGUaigoWmye3l-SEBRiU9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});